INCLUDE(ExternalProject)

SET(SDL2_PREFIX ${PROJECT_BINARY_DIR}/sdl2)
set(SDL2_CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX:PATH=${DMG_DEPENDENCIES_DIR}")

ExternalProject_Add(sdl2
    PREFIX ${SDL2_PREFIX}
  
	DOWNLOAD_COMMAND git submodule update --init -- ${CMAKE_CURRENT_SOURCE_DIR}/sdl2
	INSTALL_DIR ${DMG_DEPENDENCIES_DIR}
	SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/sdl2
    CMAKE_ARGS ${SDL2_CMAKE_ARGS}
)
